module Cockroach
  module Source
    class Model
      attr_reader :model

      def initialize model
        @model = model
      end

      # Find among the record generated by this node.
      # Returns ORM instance object
      def find id
        model.find id
      end

      # Returns a random record, among generated.
      def sample
        model.order('RAND()').first
      end
    end
  end
end