module Cockroach
  module Source
    class Model < Base
      alias_method :model, :source
      
      protected

      # Returns a random record, among generated.
      def get_sample
        if @options.blank?
          model.order('RAND()').first
        else
          if @options.has_key?("id")
            find @options["id"]
          elsif @options.has_key?("conditions")
            model.order('RAND()').where(@options["conditions"]).first
          end
        end
      end

      # Find among the record generated by this node.
      # Returns ORM instance object
      def find id
        model.find id
      end
    end
  end
end