module Cockroach
  module Source
    class Model
      attr_reader :model

      def initialize model, options = {}
        @model = model
        @options = options
      end

      # Returns a random record, among generated.
      def sample
        if @options.blank?
          model.order('RAND()').first
        else
          if @options.has_key?("id")
            find @options["id"]
          elsif @options.has_key?("conditions")
            model.order('RAND()').where(@options["conditions"]).first
          end
        end
      end

      protected

      # Find among the record generated by this node.
      # Returns ORM instance object
      def find id
        model.find id
      end
    end
  end
end