module Cockroach
  module Source
    class Node
      attr_reader :node

      def initialize node
        @node = node
      end

      # Find among the record generated by this node.
      # Returns ORM instance object
      def find id
        return nil if node.ids.empty?
        node.send(:orm_class).find id
      end

      # Returns a random record, among generated.
      def sample
        return nil if node.ids.empty?
        id = node.ids.sample
        node.send(:orm_class).find id
      end
    end
  end
end