module Cockroach
  module Source
    class Node < Base
      alias_method :node, :source
      
      protected

      # Returns a random record, among generated.
      def get_sample
        return nil if node.ids.empty?
        id = node.ids.sample
        find id
      end

      # Find among the record generated by this node.
      # Returns ORM instance object
      def find id
        return nil if node.ids.empty?
        node.send(:orm_class).find id
      end
    end
  end
end